sudo: required
language: python
python:
    - "3.6"

env:
    global:
        - PACKAGE="BracketGuard"
        - SUBLIME_TEXT_VERSION="3"
        - UNITTESTING_TAG="master"

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests
